name: Generate Document & Deploy to Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Generate Document
      run: |
        pip install pipenv
        pipenv sync
        pipenv run mkdocs build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true
